-- function ENT:IsPlayerStationary() end
-- function ENT:IsPlayerApproaching() end
-- function ENT:IsPlayerRetreating() end
-- function ENT:IsPlayerStrafing() end
-- function ENT:IsPlayerCirclingBot() end
-- function ENT:GetPlayerApproachSpeed() end
-- function ENT:HasPlayerRecentlyChangedDirection() end
-- function ENT:GetPlayerRecentPathDirection() end
